server:
  port: 9090
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.31.204.247:3306/notebook?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: T_dl123456
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
 