spring:
   datasource:
#      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.224:3306/test?characterEncoding=utf8
      username: root
      password: root
   jpa:
      show_sql: true
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            format_sql: true        